- name: Update Debian-based hosts
  hosts: all
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
